http://localhost:4000/

###

http://localhost:4000/status

###

http://localhost:4000/blocks

###

POST http://localhost:4000/blocks

{
    "message": "Mine me!"
}

http://localhost:4000/blocks/c04b346076c8f776155b2ea6b9bd7e5a17e2180a77656dcaa3b598846a067499

###
POST http://localhost:4000/transactions

{
    "to":"lynn",
    "amount":65
}
###
http://localhost:4000/mempool
###

http://localhost:4000/balance/nico?total=true
